### ISSUE TITLE
Not compatible with matomo 5.0.0

### ISSUE THREAD

**Issue by michnovka** [ip2location/ip2location-piwik#100]
The current version of plugin is incompatible with matomo 5.0.0 release

**Comment by ip2location** [comment]
May I know what version of the plugin you are installed?

The current version [5.1.0](https://github.com/ip2location/ip2location-piwik/releases/tag/5.1.0) is built for Matomo 5.x.

**Comment by linuxpac** [comment]
I confirm that with Matomo 5 and with the latest version of your plugin (5.1.0) there are problems. In fact, I have noticed that, in the maps, it no longer indicates the regions of Italy, although it detects them and shows them correctly in the table statistics.

**Comment by ip2location** [comment]
@linuxpac Issue due to outdated ISO 3166-2 Subdivision Codes. It has been updated in the latest version.
