### ISSUE TITLE
Seeing error message when trying to use local bin file 

### ISSUE THREAD

**Issue by Escondido** [ip2location/ip2location-piwik#102]
I downloaded DB9.LITE and DB1.LITE IPv6 bin files. I prefer the former, if possible. Made sure both files were transferred using binary with Winscp. Both times I saw the following message after saving, "Your IP2Location BIN file version is outdated. Please visit http://www.ip2location.com to download the latest BIN file."  

That doesn't make sense to me because I just created the account, so I assume they've been updated. before uploading the files.  Under the database path I see the following. 

Absolute path to BIN file. Example: /home/matomo/htdocs/matomo.mydomain.com/misc/IP-COUNTRY.BIN

But the actual files are 
/home/matomo/htdocs/matomo.mydomain.com/misc/IP2LOCATION-LITE-DB9.IPV6.BIN
/home/matomo/htdocs/matomo.mydomain.com/misc/IP2LOCATION-LITE-DB1.IPV6.BIN

Both IPv4 versions work fine after saving though. I'm not sure why the other files aren't working. 

Any ideas?

**Comment by ip2location** [comment]
Please remove other BIN files and keep only "IP2LOCATION-LITE-DB9.IPV6.BIN" to avoid any possible conflicts.

**Comment by Escondido** [comment]
Unfortunately, that solution doesn't work. I still see the same error message. I even tried directly downloading IP2LOCATION-LITE-DB9.IPV6.BIN and unzipping the file using the perl instructions. It only allows me to save the IPv4 file.

**Comment by ip2location** [comment]
This issue is fixed in version [5.2.1](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.1).
