### ISSUE TITLE
Many error messages showing up after activating plugin

### ISSUE THREAD

**Issue by Escondido** [ip2location/ip2location-piwik#104]
I wanted to test out DBIP/ GEOIP Vs IP2Location after making some changes.  I deactivated it for about a week. 

If I enable IPLocation.io Geolocation API Service I'm unable to select IP2Location in System>Geolocation>Location Provider. Is that normal?  In the Geolocation section it shows IP2Location as not installed, but I can see the lookup mode and my api key on the right. 

If I switch the source to IP2Location BIN Database I can select it in Location Provider, but I see a lot of error messages.  It seems to happen when I load Admin Settings Dashboard or System or Geolocation or IP2Location.   I saw a post from 2/2023 about it over at the Matomo forum, but didn't find an issue ticket.  

WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(111): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(112): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(114): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(114): Deprecated - strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(115): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(115): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(116): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(119): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(119): Deprecated - strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(120): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(123): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(123): Deprecated - strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(124): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(125): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(128): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(128): Deprecated - strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(129): Warning - Trying to access array offset on value of type bool - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)

**Comment by ip2location** [comment]
Please try the version [5.2.2](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.2) for the fixes.

**Comment by Escondido** [comment]
I only see two errors now (listed below).  Do they matter or not ? 

WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(90): Warning - Undefined property: stdClass::$response - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserCountry, Action: adminIndex, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(90): Warning - Undefined property: stdClass::$response - Matomo 5.0.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)

**Comment by ip2location** [comment]
Yes, please update to [5.2.3](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.3) for the fixes.
