### ISSUE TITLE
Error from link System > IP2Location  

### ISSUE THREAD

**Issue by camlafit** [ip2location/ip2location-piwik#105]
Hi

Matomo Version : 5.0.3
PHP :  8.2.16
Extension Version : 5.2.3

From admin dashoard, at lateral menu System >  IP2Location, I get this error :

![Capture d’écran du 2024-03-19 09-45-26](https://github.com/ip2location/ip2location-piwik/assets/209915/62d75687-9718-40a6-8d29-6e9751efd547)

**Comment by ip2location** [comment]
The issue is fixed in [5.2.4](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.4).

**Comment by camlafit** [comment]
Thanks a lot 
It's solved indeed
