### ISSUE TITLE
Display additional iplocation stats

### ISSUE THREAD

**Issue by Escondido** [ip2location/ip2location-piwik#109]
How do I get this plugin to show area code and zip code? I've been using the ip2location.io api for a few months and I know their api has those values, but I'm not seeing them in the matomo_log_conversion table ? Do I have to use a different database or maybe there is a setting I missed ? 

Thanks.

**Comment by ip2location** [comment]
I regret that these fields are currently not supported.

**Comment by Escondido** [comment]
Is that only your plugin or Matomo in general? Thinking I might be able to ChatGPT it. What file controls the api parameters that are fetched? Looks like it might be ip2location.php right ?
