### ISSUE TITLE
Call to undefined function Piwik\Plugins\IP2Location\gmp_strval()

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [ip2location/ip2location-piwik#12]
in /plugins/IP2Location/Lookup.php line 402

the script has been called with this IPv6-adress: 2a02:8070:219a:c01:c1dc:32d6:f99:7ec9

Piwik Version is 2.15

![2016-01-02 20_45_36-fotos](https://cloud.githubusercontent.com/assets/4589916/12075987/cccf4382-b196-11e5-8099-d045be955eb5.png)
![2016-01-02 20_47_45-fotos](https://cloud.githubusercontent.com/assets/4589916/12075988/ccd155be-b196-11e5-9796-7db6a90666be.png)

**Comment by ip2location** [comment]
You need to install the php5-gmp module for this to work.

**Comment by 5t0rmr1d3r** [comment]
Thanks for the answer!
I'll ask if my hoster (Strato.de) can load that plugin.
