### ISSUE TITLE
 IP2Location/API.php(42): Notice - Trying to get property of non-object - Piwik 2.15.1-b11 Support & Bugs

### ISSUE THREAD

**Issue by saxel1** [ip2location/ip2location-piwik#13]
Hi,

I just got this on Piwik 2.15.1 b11 with PHP5.6 and MySQL 5.7 :

WARNING:
/piwik/plugins/IP2Location/API.php(42):
Notice - Trying to get property of non-object - Piwik 2.15.1-b11 -
Please report this message in the Piwik forums: http://forum.piwik.org

Kind regards Axel

**Comment by ip2location** [comment]
Hi Axel,

May I know the instructions to reproduce this error?
I'm not able to reproduce this error from my side.

**Comment by ip2location** [comment]
I suspected  BIN database is not readable due permission issue. A handler has been added to catch this error.
