### ISSUE TITLE
My mistake - pleae delete the issue

### ISSUE THREAD

**Issue by tomasztomik** [ip2location/ip2location-piwik#14]
Hello,

Currently, IP2Location plugin does not offer regions information in Piwik - all regions are being reported as "Unknown".

Seems like this DB / Plugin doesn't offer Region code (only region name).
UserCountry module is looking for this code:
https://github.com/piwik/piwik/blob/master/plugins/UserCountry/Columns/Region.php#L53
https://github.com/piwik/piwik/blob/master/plugins/UserCountry/LocationProvider.php#L56

To make IP2Location plugin working with Piwik, it needs to offer also region codes, as MaxMindDB:
http://www.maxmind.com/download/geoip/misc/region_codes.csv

To make this IP2Locatation plugin compatible with Piwik mapping for the region code (like this mentioned above from MaxMind) is needed. Otherwise, this plugin seems to be useless for customers.

Regards,
Tomasz

**Comment by wronan** [comment]
@tomasztomik regionCodes are here:
https://github.com/ip2location/ip2location-piwik/blob/master/IP2Location.php#L86

**Comment by tomasztomik** [comment]
Issue can be deleted, sorry for my mistake.
