### ISSUE TITLE
Issue regarding IP2Location-Piwik after uploading the db (.BIN file)

### ISSUE THREAD

**Issue by pjs13** [ip2location/ip2location-piwik#15]
Hi friends ,

This is regarding the IP2Location plugin which i downloaded through piwik marketplace.

I followed the instructions as given in this link http://www.ip2location.com/developers/piwik
I am facing the issue after uploading the IP2Location database file (.BIN) from DB3.LITE (free) into /plugins/IP2Location/data.

**So before uploading the .BIN file i get this message:**
![image](https://cloud.githubusercontent.com/assets/17407411/13694953/4e892342-e780-11e5-957c-dd83906d17ed.png)

**And after uploading the .BIN file i get this message :**
![image](https://cloud.githubusercontent.com/assets/17407411/13694961/5d609922-e780-11e5-9771-c57a874b9888.png)

I tried using all other databases i.e DB3.LITE, DB5.LITE..which are the latest versions.
In all the case i am getting the same error message as shown above.

So Please help me to resolve this issue and help me to get the accurate working of this plugin.

Thanks in advance.

**Comment by ip2location** [comment]
Please let me know the details of the file you uploaded. The file name, file size, and file date.

**Comment by pjs13** [comment]
The filename is IP2LOCATION-LITE-DB3.BIN 
Folder size is 58.1MB which contains 
1)IP2LOCATION-LITE-DB3.BIN (bin file) 59,512 KB
2)LICENSE_LITE.TXT 2KB
3)README_LITE.TXT 1KB
 
I have downloaded the IPV4BIN (DB3.BIN) file from this link 
[http://lite.ip2location.com/database-ip-country-region-city](url)

**Comment by pjs13** [comment]
And even i am getting these warning messages without changing anything. I.e i have not even seen the IP2Location plugin's code.

![image](https://cloud.githubusercontent.com/assets/17407411/13699845/109e2cd0-e7a3-11e5-940e-9a535c6f8676.png)

**Comment by ip2location** [comment]
It seems like you BIN database is not readable due permission issue. In case it's memory sufficient issue, you may try with DB1 first.

The error has been fixed.
