### ISSUE TITLE
Update plugin.json required PHP version

### ISSUE THREAD

**Issue by tsteur** [ip2location/ip2location-piwik#16]
Hi there,

I'm Thomas from Piwik. We recently made some changes on the Marketplace and changed how versions are defined. In your plugin.json it defines:

``` json
{
        "piwik": ">=2.12.0",
        "php": "5.3.20"
    }
```

but in future updates it should include the `>=` and ideally include an upper version constraint:

``` json
{
        "piwik": ">=2.12.0,<=3.0.0-b1",
        "php": ">=5.3.20"
    }
```

Sorry for inconvenience and cheers

**Comment by ip2location** [comment]
Fixed.
