### ISSUE TITLE
Incompatible with Piwik 3

### ISSUE THREAD

**Issue by SangreNegra** [ip2location/ip2location-piwik#17]
Hello devs,

can we expect an update for your plugin that makes it compatible with Piwik 3 again?
Thanks a lot for your response.

Regards Johannes

**Comment by SangreNegra** [comment]
Thanks for the update.
But even after upgrading we don't have the IP2Location Menu item within piwik admin, and I can only select GeoIP as a location service but not my IP2Location database.
Could you please look into this? Thanks a lot!

**Comment by alfonso-romero** [comment]
Hi

Is there any update on this? It seems plugin is no longer compatible whit Piwik 3

I've tried both methods:
- upgrading from piwik v2 with plugin already installed and working, to piwik v3
- directly installing plugin v3 into a fresh piwik v3 

but none seems to work, the IP2Location menu just disappears, even tried switching between location providers but menu simply never shows up, even when clicking on plugin name listed in plugin manager, description and changelog are no longer available:
![image](https://cloud.githubusercontent.com/assets/25672970/22804132/53930352-eedd-11e6-918f-ede8f141e783.png)

Could you please guide us on this? I'd really appreciate it

Thanks in advance!

**Comment by ip2location** [comment]
The latest version no longer have independent menu.

IP2Location is combined under System >  Geolocation as an additional Location provider. Please make sure you have IP2Location installed under this section.

![2017-02-10_000262](https://cloud.githubusercontent.com/assets/6367210/22807910/746409a0-ef64-11e6-8ac9-342c758bed59.png)

If you not seeing this part, please check your error log for possible issues and report to us again.

**Comment by alfonso-romero** [comment]
Thanks for your reply

Yes I see it and it's properly installed:
![image](https://cloud.githubusercontent.com/assets/25672970/22830107/eb81042e-ef6a-11e6-9dde-d40dbcbf34d5.png)

If menu is gone, how can we access to IP2Location report now? Screenshot below is from v2, but I cannot find it anywhere in v3:

![image](https://cloud.githubusercontent.com/assets/25672970/22830156/13d4976a-ef6b-11e6-84f6-860f658cd259.png)

Is this data stored in database, so I can manually look the visitors location info? Or am I missing some extra settings to be able to see this report?

Thanks in advance!

**Comment by ip2location** [comment]
Hi, the separated menu is no longer available. The country details will now included under the "Visitor Log" like other location provider do.
