### ISSUE TITLE
Piwik version in the plugin.json file

### ISSUE THREAD

**Issue by KaanErturk** [ip2location/ip2location-piwik#18]
Recent update in the plugin.json file (see https://github.com/ip2location/ip2location-piwik/commit/6679139c4d186d7589567a1de9158fdddecd7227) overrides the Piwik v2 requirement and makes the plugin installable only on Piwik v3.

It should be `>=2.12.0,<=4.0.0-b1` instead.

**Comment by ip2location** [comment]
Thanks, we are working on it.
