### ISSUE TITLE
Location not working after upgrade to v3: unpack(): Type C: not enough input

### ISSUE THREAD

**Issue by ev0lister** [ip2location/ip2location-piwik#19]
Hi,

after upgrading to IP2Location v3 I get the following warning (and wrong location outputs):

`WARNING: /var/www/piwik/plugins/IP2Location/lib/IP2Location.php(1118): Warning - unpack(): Type C: not enough input, need 1, have 0 - Piwik 3.0.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)`

I have downloaded most current DBv9 (v4 and v6) and extracted them to piwik/misc as requested. Seems like there is a bug with reading the contents of the database.

As location I get:

termaritzburg Pietra Ligure PietracatellaPietralungaPietrapaolaPietrariPietrasantaPietrosellaPi

Org: unbekannt
ISP: unbekannt
Refresh
Database File: IP2LOCATION-LITE-DB9.BIN

File permissions:
```
-rw-rw-r--  1 www-data www-data 106139446 Dec 15 20:00 IP2LOCATION-LITE-DB9.BIN
-rw-rw-r--  1 www-data www-data 121104943 Dec 15 20:00 IP2LOCATION-LITE-DB9.IPV6.BIN
```

Best regards
Stefan

**Comment by ip2location** [comment]
It seems like your uploaded the files in ASCII mode. Please upload the BIN files in binary mode.

**Comment by ev0lister** [comment]
Hi, unfortunately this seems not to be the issue. I tried several ways to upload the file:

- Upload zip via SFTP (bin)
- Extract file locally
- Upload BIN file directly

all have the same result. Any other ideas? Using your files for quite some time, so it used to work like this before with v<3.0 of the plugin.

**Comment by ip2location** [comment]
Hi, please contact us at support@ip2location.com with your IP for further investigation.

**Comment by ev0lister** [comment]
Will do, but it seems that it has something to do with my IPv6 address. When using the piwik admin console with a ipv4 address it is working.

**Comment by DaSchTour** [comment]
I've the same issue. Also uploaded the ZIP and unziped on the server. Same result. IPv4 works fine but IPv6 gives strange results.
