### ISSUE TITLE
Piwik fatal error when setting geolocation with IP2

### ISSUE THREAD

**Issue by piedagile** [ip2location/ip2location-piwik#20]
Hello, happy new year

I recently uninstalled free GeoIP2 that doesn’t work well with IPV6 (no city info)
Then,
I installed  the last IP2Location plugin from Piwik 3.0.0 marketplace (dated dec. 23 2016)
Then I uploaded IP2LOCATION-LITE-DB3.IPV6.BIN (dated jan 1st 2017) to /misc with filezilla in binary format
piwik crashes into the fatal error everytime I go to Settings/Geolocation.

"Call to undefined function IP2Location\bcadd() in /srv/data/web/vhosts/www.imagimuse.net/htdocs/piwik/plugins/IP2Location/lib/IP2Location.php 992 using PHP 5.6.25-1+0~20160829102648.9+jessie~1.gbpbb5cad"

No error if I remove the database. 
Same issue after deactivating-reactivating IPV2 plugin. Same issue if the plugin is manually uploaded.

The rest of piwik is working fine.
Have you any idea of what I should do?

Regards

**Comment by ev0lister** [comment]
Hi, bcadd is  part of a php module (php-bcmath), can you check whether php-bcmath is available on your platform?

**Comment by ip2location** [comment]
As suggested by @ev0lister, please install the php-bcmath on your server to keep this plugin working.

**Comment by piedagile** [comment]
Thanks, I verified this and restarted the server instance.
The php-bcmath is on: http://simple.gandi-test.fr/phpinfo.php#module_bcmath <http://simple.gandi-test.fr/phpinfo.php#module_bcmath>

But the same fatal error today. Should I fully reinstall Piwik and IP2? Something to do with the piwik mysql database?

Regards

A fatal error occurred

The following error just broke Piwik (v3.0.0):

Call to undefined function IP2Location\bcadd()
in
/srv/data/web/vhosts/www.imagimuse.net/htdocs/piwik/plugins/IP2Location/lib/IP2Location.php line 992

Troubleshooting

Follow these steps to solve the issue or report it to the team:
If you have just updated Piwik to the latest version, please try to restart your web server. This will clear the PHP opcache which may solve the problem.
If this is the first time you see this error, please try refresh the page.
If this error continues to happen, we appreciate if you send the error report <mailto:hello@piwik.org?subject=Fatal%20error%20in%20Piwik%203.0.0&body=Call%20to%20undefined%20function%20IP2Location%5Cbcadd%28%29%20in%20%2Fsrv%2Fdata%2Fweb%2Fvhosts%2Fwww.imagimuse.net%2Fhtdocs%2Fpiwik%2Fplugins%2FIP2Location%2Flib%2FIP2Location.php%20992%20using%20PHP%205.6.25-1+0%7E20160829102648.9+jessie%7E1.gbpbb5cad> to the Piwik team.
Further troubleshooting

If this error continues to happen, you may be able to fix this issue by disabling one or more of the Third-Party plugins. You can enable them again in the Plugins <http://www.imagimuse.net/piwik/index.php?module=CorePluginsAdmin&action=plugins> or Themes <http://www.imagimuse.net/piwik/index.php?module=CorePluginsAdmin&action=themes> page under settings at any time. Based on the error message, the issue is probably caused by the plugin IP2Location/lib.

IP2Location	deactivate <http://www.imagimuse.net/piwik/index.php?module=CorePluginsAdmin&action=deactivate&pluginName=IP2Location&nonce=1887b819d027340c1bce079ea86b7a8d>                         
If this error still occurs after disabling all plugins, you might want to consider uninstalling some plugins. Keep in mind: The plugin will be completely removed from your platform.

ExampleRssWidget	uninstall <http://www.imagimuse.net/piwik/index.php?module=CorePluginsAdmin&action=uninstall&pluginName=ExampleRssWidget&nonce=6f768a72e515c6610fd804addc712cf7>

**Comment by ip2location** [comment]
Can you please confirme that simple.gandi-test.fr and www.imagimuse.net is hosted on same server?

I found that both of them resolved to different IP.
