### ISSUE TITLE
No Menu after update to 2.3.0

### ISSUE THREAD

**Issue by thob** [ip2location/ip2location-piwik#21]
Updated to 2.3.0, got succes message after activating but don't get any Menu entry (and no data)

Piwik Version: 3.0.0
MySQL Version: 5.1.73
PHP-Version: 7.0.5
Latest DBs in /data dir

**Comment by ip2location** [comment]
Please use 3.0.0 plugin for Piwik 3.0.0.
Menu no longer available in the latest version, it will be a part of geolocation plugin now.

**Comment by thob** [comment]
Ok, v3 is in but I don't get no Menu either

**Comment by thob** [comment]
Ah sorry, I didn't get it. And the DB need to go to /misc, right?

**Comment by ip2location** [comment]
Yes. The directory is changed to prevent database file from being replaced during updates.

Do let me know if you able to get this working again.
