### ISSUE TITLE
After upgrading to version 3.1.0 geo information is wrong

### ISSUE THREAD

**Issue by 8sol** [ip2location/ip2location-piwik#22]
Hi all, 

some days  before I have successfully upgrade to latest plugin version 3.1.0. Since the upgrade, it seems to be the GEO informations are wrong. Always the same information is provided:

`(37.406, -122.079)
Mountain View, CA
United States`

I have repeat the test with different german IP addresses but the GEO ip information is always the same. 

Current database is --> IP2LOCATION-LITE-DB11.BIN 
database date is: 2017-05-30
Piwik Version: Piwik 3.0.4

Can anyone help on this issue? 

Thank you in advanced

**Comment by chrislim2888** [comment]
Sorry about this issues that due to our testing data. It has been removed.
