### ISSUE TITLE
Blocking bug after updating the IP2Location plugin (June 23, '17)

### ISSUE THREAD

**Issue by ZijOok** [ip2location/ip2location-piwik#23]
Hello,

I have been using the Piwik IP2Location pluging for months, even years without any issue. I use the DB3 lite DB for IPv6. Countries and cities have always been reported in a satisfactoy way. Since the yesterday ( June 23, '17) update to the new version of the plugin, cities and countries are no longer reported correctly, all the IP addresses are reported as belonging to the US. My own IP address was previously reported as in Belgium as it is and -out of of sudden-, it was reported in the US, Montana. 
The DB3 bin file remained unchanged. 
No reload of the DB3 file could solve the issue.

I guess there is an issue whith the query of the DB3 file by the new plugin. 

Is there any way to roll back to the previous versoion of the plug in before a fiw is available for that issue ?

Patricia.

**Comment by ZijOok** [comment]
Foudn another techie girl with exactly the same issue:
https://forum.piwik.org/t/depuis-la-derniere-mise-a-jour-du-plugin-ip2location/24671

**Comment by ip2location** [comment]
Have you tried with version 3.1.1?

**Comment by ZijOok** [comment]
The version available on the MarketPlace is 3.1.0 and this is the version that was automatically installed or upgraded to.
Please provide me with the link to the 3.1.1 file for download and manual installation and I'll test with that release
 
Thanks
 
Pat

**Comment by ip2location** [comment]
It seems like the link in market place is updated slower than expected.

Here is the download link:

https://github.com/ip2location/ip2location-piwik/archive/3.1.1.zip

**Comment by ZijOok** [comment]
Hello,
 
 
The point is, the version packaged in the zip file ip2location-piwik-3.1.1.zip seems to be version 3.1.0 NOT 3.1.1
I include the json file included in the package and it reports this version as 3.1.0.
 
Or is it version 3.1.1 and is it just a problem of version control reporting? If this is the case, it could be that the version served on the market place is v 3.1.1  but reported as v 3.1.0
 
Thank you in adavnce for making me smart about this.
 
Patricia

**Comment by manyk** [comment]
@ZijOok that archive indeed contains the last version 3.1.1.
The problem is that nobody updated the version string. Maybe this generates an issue with Piwik install too and deter it from picking automatically the new version and present it for update. I remember this is not the first time a new version is ready but the version string is not updated.

**Comment by seikan** [comment]
@manyk Thanks for pointing out the issue to correct direction. I'm take note of this in next release.
