### ISSUE TITLE
Warning - unpack(): Type V: not enough input, need 4, have 0 - Piwik 3.0.4

### ISSUE THREAD

**Issue by welcometopwn** [ip2location/ip2location-piwik#25]
Hello,

I installed the plugin via Piwik Marketplace and uploaded the .bin files in /piwik/misc.

Now when I want to access System > IP2Location I get spammed with the following error:

`WARNING: /.../piwik/plugins/IP2Location/lib/IP2Location.php(1106): Warning - unpack(): Type V: not enough input, need 4, have 0 - Piwik 3.0.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)`

Thanks in advance!

**Comment by ip2location** [comment]
Fixed.
