### ISSUE TITLE
WARNING: /var/www/html/plugins/IP2Location/lib/IP2Location.php(1121): Warning - unpack(): Type C: not enough input, need 1, have 0

### ISSUE THREAD

**Issue by takehora** [ip2location/ip2location-piwik#26]
Hello,

I am using DB3-IP-COUNTRY-REGION-CITY.BIN.
When I tried to configure plug-in, errors were shown as bellow.

`WARNING: /var/www/html/plugins/IP2Location/lib/IP2Location.php(1121): Warning - unpack(): Type C: not enough input, need 1, have 0 - Piwik 3.0.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)`

Please advise how I can fix it.

Thank you,
Tak

**Comment by ip2location** [comment]
May I know the version of your plugin?

**Comment by takehora** [comment]
3.1.3.

**Comment by ip2location** [comment]
Can you please try with version 3.1.4?

**Comment by takehora** [comment]
Thank you for uploading new version shortly.
It works!

Thank you!
