### ISSUE TITLE
IP2Location stops Piwik working

### ISSUE THREAD

**Issue by Tonyt8** [ip2location/ip2location-piwik#27]
Hi 

When I install the IP2Location plugin my installation of Piwik stops working. I have made many attempts. Each time I must do a clean install of Piwik to get Piwik running again. Please could you advise what is going wrong.
Regards,
Tony

**Comment by ip2location** [comment]
Hi, may I know what kind of error message you received during the installation?

**Comment by ip2location** [comment]
@Tonyt8 It that possible to let me know the version of your Piwik? Also the server error log so we can identify the issue.
