### ISSUE TITLE
Unpack v3.1.8 - Matomo 3.1.8

### ISSUE THREAD

**Issue by raponiwalter** [ip2location/ip2location-piwik#28]
WARNING: /var/www/html/piwik/plugins/IP2Location/lib/IP2Location.php(1110): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 3.8.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

In the plugin settings i have this error: Your IP2Location BIN file version is outdated. Please visit http://www.ip2location.com to download the latest BIN file."

But have a fresh bin file downloaded.

**Comment by ip2location** [comment]
It seems like you have uploaded a corrupted BIN database file. Can you make sure you have re-upload the BIN file as binary?

**Comment by raponiwalter** [comment]
i downloaded it with wget from the server and unziped. Looks like via ftp works better.
Sorry for the ticket.

Hope it will help someone else in the future.

Cheers!
