### ISSUE TITLE
Ip2location not working after update to v3.1.10 

### ISSUE THREAD

**Issue by maisen20** [ip2location/ip2location-piwik#29]
Hi

After update to v3.1.10 the plugin “ip2location” no longer works.

I’m getting following error:

> [28-May-2019 05:52:34 UTC] PHP Fatal error: Uncaught Error: Class ‘IP2Location\Database’ not found in […]/plugins/IP2Location/LocationProvider/IP2Location.php:86
> Stack trace:
> #0 […]/plugins/UserCountry/VisitorGeolocator.php(145): Piwik\Plugins\IP2Location\LocationProvider\IP2Location->getLocation(Array)
> #1 […]/plugins/UserCountry/VisitorGeolocator.php(115): Piwik\Plugins\UserCountry\VisitorGeolocator->getLocationObject(Object(Piwik\Plugins\IP2Location\LocationProvider\IP2Location), Array)
> #2 […]/plugins/UserCountry/Columns/Base.php(50): Piwik\Plugins\UserCountry\VisitorGeolocator->getLocation(Array, true)
> #3 […]/plugins/UserCountry/Columns/City.php(43): Piwik\Plugins\UserCountry\Columns\Base->getLocationDetail(Array, ‘city_name’)
> #4 […]/core/Tracker/Visit.php(460): Piwik\Plugins\UserCountry\Columns\City->onNewVisit(Object(Piwik\Tracker\Request), Object in […]/plugins/IP2Location/LocationProvider/IP2Location.php on line 86

When i click on “ip2location” in the matomo-settings, i’m getting following error/report:

> A fatal error occurred
> 
> The following error just broke Matomo (v3.9.1):
> 
> Class ‘IP2Location\Database’ not found
> in […]/plugins/IP2Location/API.php line 56
> Troubleshooting
> 
> Follow these steps to solve the issue or report it to the team:
> If you have just updated Matomo to the latest version, please try to restart your web server. This will clear the PHP opcache which may solve the problem.
> If this is the first time you see this error, please try refresh the page.
> If this error continues to happen, we appreciate if you send the error report to the Matomo team.

Does someone have the same issue?

Best regards
maisen20

**Comment by ip2location** [comment]
Sorry for the issue. It has been fixed in 3.1.11.
