### ISSUE TITLE
syntax requires PHP 7.1

### ISSUE THREAD

**Issue by Findus23** [ip2location/ip2location-piwik#30]
Hi,

Someone on the forum reported that the latest version doesn't work for them.

https://forum.matomo.org/t/ip2location-not-working-after-update-to-v3-1-10/33030/7?u=lukas

According to PHPstrom this assignment syntax is only availible since PHP 7.1
https://github.com/ip2location/ip2location-piwik/blob/35a31874b663d6b7d99337c53704e9532b51c70a/lib/IP2Location.php#L890

**Comment by luskin72** [comment]
Yes I confirm... Running Debian 9 with PHP 7.0.33-0+deb9u3 I get:

syntax error, unexpected '=' in /var/www/piwik/plugins/IP2Location/lib/IP2Location.php 890 using PHP 7.0.33-0+deb9u3

A fatal error occurred

                The following error just broke Matomo (v3.9.1):
            
syntax error, unexpected '='
in /var/www/piwik/plugins/IP2Location/lib/IP2Location.php line 890

**Comment by ip2location** [comment]
It has been fixed in 3.1.12.

**Comment by luskin72** [comment]
Same problem in 3.1.12 here:

A fatal error occurred

The following error just broke Matomo (v3.9.1):

syntax error, unexpected '='
in /var/www/piwik/plugins/IP2Location/lib/IP2Location.php line 976

**Comment by ip2location** [comment]
Can you try with version 3.1.13?

**Comment by luskin72** [comment]
Just installed 3.1.14... seems ok now :-)
[Yes. we can! :D]
