### ISSUE TITLE
Class was renamed \IP2Location\IP2Location?

### ISSUE THREAD

**Issue by renenieuwenhuizen** [ip2location/ip2location-piwik#31]
I think you renamed the class \IP2Location\Database to \IP2Loaction\IP2Location so API.php should reflect the same.

https://github.com/ip2location/ip2location-piwik/blob/0311fb0accb3b2405a8f117caab26aa6dc1b571b/API.php#L56

**Comment by renenieuwenhuizen** [comment]
Same for:

https://github.com/ip2location/ip2location-piwik/blob/0311fb0accb3b2405a8f117caab26aa6dc1b571b/LocationProvider/IP2Location.php#L86

https://github.com/ip2location/ip2location-piwik/blob/0311fb0accb3b2405a8f117caab26aa6dc1b571b/LocationProvider/IP2Location.php#L87

https://github.com/ip2location/ip2location-piwik/blob/0311fb0accb3b2405a8f117caab26aa6dc1b571b/LocationProvider/IP2Location.php#L134

https://github.com/ip2location/ip2location-piwik/blob/0311fb0accb3b2405a8f117caab26aa6dc1b571b/LocationProvider/IP2Location.php#L178

**Comment by ip2location** [comment]
Sorry, it was a typo. Fixed in 3.1.14.
