### ISSUE TITLE
Control the WS package while using IP2Location @Matomo (Piwik)

### ISSUE THREAD

**Issue by itseoconsulting** [ip2location/ip2location-piwik#33]
While a test setup with https://github.com/ip2location/ip2location-piwik I didnt find any GUI option to control the WS packages according to https://www.ip2location.com/web-service/ip2location -> Pricing

E.g. switching from WS6 to WS4 to manage credit spending 

I was looking into https://github.com/ip2location/ip2location-piwik/blob/f4a0dfd81deab89ca156d2504415c7bf497cc5e0/LocationProvider/IP2Location.php#L69

**Comment by ip2location** [comment]
Hi, it's not possible to switch the WS to a lower package as we need the coordinates for map plotting purposes.

**Comment by itseoconsulting** [comment]
Please elaborate what you mean with "map plotting purposes" at Matomo.
Thank you!
