### ISSUE TITLE
Warning - unpack(): Type C: not enough input, need 1, have 0

### ISSUE THREAD

**Issue by saphirblanc** [ip2location/ip2location-piwik#34]
Hello,
I'm getting the following messages when browsing on the CoreAdminHome module's page.

`WARNING: /var/www/piwik/plugins/IP2Location/lib/IP2Location.php(1052): Warning - fread(): Length parameter must be greater than 0 - Matomo 3.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)`

`WARNING: /var/www/piwik/plugins/IP2Location/lib/IP2Location.php(1123): Warning - unpack(): Type C: not enough input, need 1, have 0 - Matomo 3.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)`

Is it related to IP2Location or should I only report on Matomo forum?

Thank you,
Yann

**Comment by ip2location** [comment]
Please reupload the BIN database and make sure it has the read permission by your web server. It seems like your BIN database file was corrupted.

**Comment by xoai** [comment]
Hi @ip2location 

I got this message:

`Warning: unpack(): Type V: not enough input, need 4, have 0 in /srv/www/abc.com/vendor/ip2location/ip2location-php/IP2Location.php on line 1663`

I tried to redownload the BIN database many times and I am sure it's readable by web server. Not sure what's problem here.

Btw, when I tried to use SHARED_MEMORY, it's also failed with error message:

`Warning: shmop_read(): start is out of range in /srv/www/abc.com/vendor/ip2location/ip2location-php/IP2Location.php on line 1594`

`Warning: unpack(): Type V: not enough input, need 4, have 0 in /srv/www/abc.com/vendor/ip2location/ip2location-php/IP2Location.php on line 1663`

**Comment by ip2location** [comment]
It seems like your BIN file is corrupted. Please make you have sufficient disk space and decompress the .BIN file from your downloaded package.

Can I know the BIN file name and file size?
