### ISSUE TITLE
ip2location-piwik set the wrong segment paraments in Location filter. 

### ISSUE THREAD

**Issue by Creling** [ip2location/ip2location-piwik#38]
Hello:
When I set the time period to `day`:
![image](https://user-images.githubusercontent.com/43109504/87214554-344d9d80-c360-11ea-9063-ad65487f703a.png)
the segment paraments are like these and the result is correct:
![image](https://user-images.githubusercontent.com/43109504/87214571-59421080-c360-11ea-86a8-4f725d0bec93.png)

---

But when I set the time period to `year`:
![image](https://user-images.githubusercontent.com/43109504/87214591-81ca0a80-c360-11ea-9f83-b5ecbb116ad2.png)
the segment paraments are like these and the result is null:
![image](https://user-images.githubusercontent.com/43109504/87214600-a0c89c80-c360-11ea-8e08-0a9724545be3.png)

**Comment by ip2location** [comment]
Hi, you cannot generate logs before the plugin installed as the format is not compatible.

**Comment by Creling** [comment]
Hello:
I have installed the plugin when I open this ticket and in the second picture, the filter works well.
But when I set the time period to `year`, as shown in the 3rd picture, the filter doesn't work.

**Comment by ip2location** [comment]
We cannot reproduce the issue from our side. It might be wrong format in your visitor log.

You may directly send us your visitor log to supprt@ip2location.com for investigation.

**Comment by Creling** [comment]
Well, I can provide a user account of the matomo instance, will that be helpful?

**Comment by ip2location** [comment]
Yes. Please contact us directly at supprt@ip2location.com for investigation.
