### ISSUE TITLE
 Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.3.1

### ISSUE THREAD

**Issue by FMTHouston** [ip2location/ip2location-piwik#39]
Getting this error after fresh install.

WARNING: /***/***/***/***/plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.3.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)

Any ideas as to why?

**Comment by ip2location** [comment]
It seems like your BIN database is corrupted, please reupload it and try again.
