### ISSUE TITLE
Translations using Weblate

### ISSUE THREAD

**Issue by Findus23** [ip2location/ip2location-piwik#40]
Hello,

Lukas from Matomo team here. We are currently in the process of moving our translations from Transifex to Weblate (https://github.com/matomo-org/matomo/issues/17907).
As Weblate makes it easier to add a git repository as a component and merge back updated translations via pull requests, I thought it would be great if more plugins in Matomo were available in the users languages if someone is interested in translating them.

If you are interested in adding your plugin, simply comment here, and I'll help you with the setup.

**Comment by ip2location** [comment]
Yes, we are interested. Can you please help us to proceed with the setup?

**Comment by Findus23** [comment]
Hi,

I created the component on weblate: https://hosted.weblate.org/projects/matomo/communityplugin-ip2location/

Soon you should receive a pull request with two minor fixes I did to the source string. If you wait at most 24h all other supported languages should also be added.

Afterwards Weblate will always create Pull Requests whenever the translations changed and you can e.g. merge them before releases.

The only thing you need to do is the following:
For Weblate to be notified anytime the source strings change, you need to set up a Webhook. For this go into the settings of this repository and create a new webhook with `https://hosted.weblate.org/hooks/github/` as the Payload URL. You can leave all other settings at the default.

**Comment by ip2location** [comment]
Thanks
