### ISSUE TITLE
IP2Location not working as expected

### ISSUE THREAD

**Issue by suz-vdk** [ip2location/ip2location-piwik#47]
get loads of errors including : 
Warning - unpack(): Type V: not enough input, need 4, have 0
What is missing?

Complete log:

WARNING: /plugins/IP2Location/lib/IP2Location.php(1676): Warning - unpack(): Type C: not enough input, need 1, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(145): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(141): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(136): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1676): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(150): Notice - Trying to access array offset on value of type bool - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode:

**Comment by chrislim2888** [comment]
The issues has been fixed. Can you please get the latest v4.0.3 and try?

**Comment by suz-vdk** [comment]
How can I apply this in Piwik?
