### ISSUE TITLE
Incorrect .BIN file picked

### ISSUE THREAD

**Issue by michnovka** [ip2location/ip2location-piwik#49]
I installed also IP2Proxy addon and uploaded my 2 BIN files into `misc/` folder

```
-rw-r--r--  1 root  root   96137254 Nov 29 17:00 IP2PROXY-IP-PROXYTYPE-COUNTRY.BIN
-rw-r--r--  1 root  root  379783309 Nov  1 13:00 IPV6-COUNTRY-REGION-CITY-ISP.BIN
```
However this results in issues, as the IP2Location plugin picks IP2Proxy BIN file (maybe as its alphabetically first?) for IP2Location and this makes ip2location lookups broken.

**Comment by ip2location** [comment]
Please rename the file so it gets sorted first. We will add a custom input in the next version.

**Comment by michnovka** [comment]
hi, ok thanks. But dont you think this issues should stay open until its resolved with actual push?

**Comment by ip2location** [comment]
We already have a new version released after my comment. Please check the version [4.0.6](https://github.com/ip2location/ip2location-piwik/releases).

**Comment by michnovka** [comment]
I use 4.0.7 and I still get IP2PROXY BIN picked. I cant find the option to specify any other file. Where is it?

**Comment by michnovka** [comment]
I see, you left the bad foreach loop after the new one. There should be some check if BIN was picked in the first foreach loop, the do not run the 2nd one. See here: https://github.com/ip2location/ip2location-piwik/commit/7248b2d8320f29d0dfa2859c58b0d4428e7641ce#r61224005

**Comment by michnovka** [comment]
I fixed the bug with this PR - https://github.com/ip2location/ip2location-piwik/pull/51

**Comment by ip2location** [comment]
The pull has been released, thanks.
