### ISSUE TITLE
Matomo IP2Location version 4.0.6

### ISSUE THREAD

**Issue by suz-vdk** [ip2location/ip2location-piwik#50]
The version 4.0.6 is automatically installed with the latest upgrade from Matomo. However, it does not work. How can I downgrade to 4.0.5?

**Comment by ip2location** [comment]
Are you getting any error messages?

**Comment by suz-vdk** [comment]
Yes I do


WARNING: /plugins/IP2Location/lib/IP2Location.php(1676): Warning - unpack(): Type C: not enough input, need 1, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(145): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(141): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(136): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1676): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
× 
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(150): Notice - Trying to access array offset on value of type bool - Matomo 4.6.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)

**Comment by ip2location** [comment]
It looks like your IP2Location BIN database file is corrupted. Please reupload it to /misc directory.

**Comment by suz-vdk** [comment]
We have a web subscription

**Comment by ip2location** [comment]
Can you check your Matomo Settings > System > IP2Location, if IP2Locaiton Web Service is selected?

**Comment by suz-vdk** [comment]
Yes it is

**Comment by ip2location** [comment]
Please remove any BIN files under /misc folder.

**Comment by suz-vdk** [comment]
Thanks I think it took care of the errors. For some reason one bin was installed with the update

The latest release also took care of the provider not been detected. I can now see the provider. 

Thank you for the support.
