### ISSUE TITLE
IP2Location broken after installing Matomo 4.8.0

### ISSUE THREAD

**Issue by suz-vdk** [ip2location/ip2location-piwik#57]
WARNING: /plugins/IP2Location/lib/IP2Location.php(1676): Warning - unpack(): Type C: not enough input, need 1, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(145): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(141): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(136): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1676): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1663): Warning - unpack(): Type V: not enough input, need 4, have 0 - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/lib/IP2Location.php(1602): Notice - fread(): read of 8192 bytes failed with errno=21 Is a directory - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
×
WARNING: /plugins/IP2Location/LocationProvider/IP2Location.php(150): Notice - Trying to access array offset on value of type bool - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode:

**Comment by ip2location** [comment]
It looks like your BIN file is corrupted. Please reupload the BIN database and give read permission for your web server.

**Comment by suz-vdk** [comment]
Dear support,
Your standard answer is not satisfactory.

I do not use the bin. I have a web subscription. 

Looking for real support with smart questions.

**Comment by ip2location** [comment]
Your error is coming from a BIN lookup. Please send us a screenshot of your IP2Locaiton Settings page.

**Comment by ip2location** [comment]
This issue is resolved in version 4.0.9.
