### ISSUE TITLE
Can't change Location provider to IP2Location

### ISSUE THREAD

**Issue by arsenhovhannisyan** [ip2location/ip2location-piwik#71]
we using Bitnami docker version of Matomo , Plugin is installed and database is configured , but in geolocation can't change plugin provider to IP2Locations because it shows Not Installed. See screenshots attached.

Matomo version: 4.10.1
MySQL version: 5.7.37-google
PHP version: 8.0.19

![IP2Location_config](https://user-images.githubusercontent.com/56592747/185393163-14b59e4b-5cff-4ecb-8193-c63a6ba5dbbd.png)
![Loc_provider](https://user-images.githubusercontent.com/56592747/185393169-6f87351c-f878-4b26-ad51-50a0ea3140a1.png)
![Matomo_plugins](https://user-images.githubusercontent.com/56592747/185393173-1f0507fd-0dd0-4ce3-bee3-bad9fd08d570.png)

**Comment by ip2location** [comment]
Please try to clear your Matomo cache and try again. 

https://matomo.org/faq/how-to/faq_25548/

**Comment by arsenhovhannisyan** [comment]
> Please try to clear your Matomo cache and try again.
> 
> https://matomo.org/faq/how-to/faq_25548/

The same issue, Matomo directory is not mounted to remote volume so the cache is deleted after each restart . 
In the Bitnami version, the matomo directory is "/opt/bitnami/matomo" but plugins, misc is in the remote-mounted "/bitnami/matomo" directory.

**Comment by ip2location** [comment]
Can you please check the permission of "plugins/IP2Location/LocationProvider/IP2Location.php" is accessible by your web server?
