### ISSUE TITLE
Version 4.1.1 seems to have only partially fixed the issue from 4.1.0

### ISSUE THREAD

**Issue by KZeni** [ip2location/ip2location-piwik#76]
See https://github.com/ip2location/ip2location-piwik/pull/75 for more details & a proposed fix (simply took the fix from 4.1.1 of swapping `StaticContainer::get('path.ip2location')` for `PIWIK_DOCUMENT_ROOT . '/misc/'` like it was before 4.1.0 and applied it in other spots where it came up.)

**Comment by KZeni** [comment]
Of course, the goal might be to switch to using `StaticContainer::get('path.ip2location')` for this, but seeing how 4.1.1 chose to have it go back to using `PIWIK_DOCUMENT_ROOT . '/misc/'` made me think that might be the best fix for now (seeing how 4.1.1 was resulting in some errors when trying to view the IP2Location setting page) until the ideal setup is ready to be embraced & is bug-free.

**Comment by ip2location** [comment]
Thank you. Will release a new version.
