### ISSUE TITLE
插件安装成功，文件也放置的没问题，但是定位不到地理位置

### ISSUE THREAD

**Issue by long1012** [ip2location/ip2location-piwik#88]
<img width="1117" alt="image" src="https://github.com/ip2location/ip2location-piwik/assets/26102173/dbdd7163-ba5b-46fd-86b6-f1a0632eaf2c">

**Comment by ip2location** [comment]
Please make sure your reverse proxy has forwarded the correct IP address to your backend web server.

**Comment by long1012** [comment]
Thank you for your reply. My access address is an IP address, will it affect the location of the address

**Comment by ip2location** [comment]
Can I know what IP is detected on your web server?

**Comment by long1012** [comment]
<img width="1389" alt="image" src="https://github.com/ip2location/ip2location-piwik/assets/26102173/f61e055c-c94c-4eb0-ba2e-b2aeef75d7a1">
Do you mean here？

**Comment by long1012** [comment]
Is it related to my service being only accessible through the internal network？

**Comment by ip2location** [comment]
The internal network will not work.  All local IP addresses are reserved without geolocation information.
