### ISSUE TITLE
Custom location for IP2Location bin files

### ISSUE THREAD

**Issue by gramakri** [ip2location/ip2location-piwik#91]
Currently, the IP2Location bin files have to be located in the source tree under `$PIWIKI_SRC/misc` . There is a whole bunch of things upstream under misc - https://github.com/matomo-org/matomo/tree/5.x-dev/misc/ . When deploying with docker, we delete the old matomo image and replace with new matomo image.  Every time we do this, we have to remember to copy over the ip2location database. `misc` cannot be mounted as a volume in docker either and be part of backup because there is already some upstream source code there.

Is it possible to set an alternate location for the IP2Location bin files? This will immensely help deployment.

**Comment by ip2location** [comment]
Thanks for the feedback. We will plan to add a custom location in the coming release.

**Comment by ip2location** [comment]
This feature was added in version [5.2.0](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.0).

**Comment by gramakri** [comment]
Thanks!
