### ISSUE TITLE
Matomo 5 compatibility

### ISSUE THREAD

**Issue by snake14** [ip2location/ip2location-piwik#94]
Dear Matomo Plugin Author,
We are excited that Matomo 5.0.0 is on the horizon, and we would greatly appreciate your assistance in ensuring that your plugin remains compatible with this upcoming release. Maintaining compatibility will enable Matomo users to seamlessly use your plugin after they upgrade to Matomo 5. (If the plugin is not updated to be compatible with Matomo 5, then whenever a user will upgrade to Matomo 5, the plugin would be automatically disabled to prevent issues.)

Updating your plugin to be Matomo 5 compatible is a straightforward process and should not require a significant time investment. You can find more information about updating your plugin at: https://developer.matomo.org/guides/migrate-matomo-4-to-5

Thank you for your ongoing support and commitment to the Matomo community. 
Your contribution is really appreciated!

The Matomo Team

PS: we’re also available to help if you have any question about making the plugin compatible.

> I took the liberty of forking this project and making the necessary changes. If you create a `5.x-dev` branch, merge [my changes](https://github.com/snake14/ip2location-piwik/tree/5.x-dev) into that branch, and create a new release, you should be good to go.

**Comment by ip2location** [comment]
A new branch **5.x-dev** with updated codes has been committed.
