### ISSUE TITLE
Bug: Composer activates and installs unwanted files 

### ISSUE THREAD

**Issue by atom-box** [ip2location/ip2location-piwik#96]
One user of Matomo reported that they installed IP2Location-piwik and immediately 
two files from Composer showed up inside their Matomo directory (in Docker).
Is it suspicious or mundane to see the following two files appear inside of Matomo directory when this plugin is installed?

- matomo/misc/composer/composer.php
- misc/others/matomo.php

**Comment by ip2location** [comment]
Can you please check the content of the composer.php?

I cannot reproduce the issue from my side.

**Comment by atom-box** [comment]
Thanks for your reply. Customer is using Docker or similar containerized deployment so it is probably the fault of the deployment code. 
**You can probably close this ticket.**
Here is the code though, to make it public (customer sent it as a screenshot to us):

![image](https://github.com/ip2location/ip2location-piwik/assets/22874146/b56c4c53-d759-47f0-9c85-757a29a17313)
